% Compile python package 'pcg_matlab'

files=["pcg_info.m", "pcg_waveform.m"];
opts = compiler.build.PythonPackageOptions(files, ...
    "PackageName",'pcg_matlab', ...
    'OutputDir', 'pcg_matlab_python', ...
    'Verbose','on', ...
    'AutoDetectDataFiles','off');
disp(opts);
compiler.build.pythonPackage(opts);