
@startuml d1
!theme cerulean-outline
autonumber "<b>[000]"
' title Main workflow
Actor User
participant "Telegram-bot" as TB
participant "Server" as S
participant "Query" as Q
participant "Worker" as W
participant "Processing" as P

User->TB:PCG
TB->S:PCG
S->S:save PCG to file
S->Q:write task
...async...
W->Q:get task
return task
W->P:task processing
return task result
W->Q:write task result
...async...
S->Q:get task
return task
S->TB:message with \nresult

@enduml

